# DBの設定ファイル

# http://localhost:8080/h2-console
# 上記URLでブラウザからアクセス可能

spring:
  datasource:
    # mem メモリのこと 起動ごとに初期化される
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    # デフォルトのname,password
    username: sa
    password: sa
  # ブラウザでh2dbを確認できる
  h2.console.enabled: true

server:
  servlet:
    session:
      cookie:
        # 秒数で指定（負の数で無限）
        # ExpiresもMax-Ageもない場合は、
        # Webブラウザのセッション終了まで有効（ブラウザを終了すると削除される）
        max-age: 3600
        # Cookieが有効なパス範囲の指定
        # 指定されたドメインに含まれるならCookieが有効
        # Domainがない場合は、現在のホストでのみ有効
        path:   /